### ISSUE TITLE
【报错信息求助】域名验证失败，验证文件浏览器可以正常访问

### ISSUE THREAD

**Issue by SpringAndMay** [mouday/domain-admin#115]
问题描述：手动部署和自动部署均能通过给定的url访问到部署的验证文件，但是点击验证始终提示：“域名验证失败”
![微信截图_20240708091543](https://github.com/mouday/domain-admin/assets/57424550/869258c0-a1e0-4813-a9db-4465c94b60bf)
系统信息：centos 7.5.1804
docker info信息：client Version：18.06.1-ce
domain_admin版本信息：1.6.37
日志信息：
2024-07-08 09:12:02 [ERROR] handler.py/error_handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/domain_admin/api/issue_certificate_api.py", line 60, in verify_certificate
    issue_certificate_service.verify_certificate(issue_certificate_id, challenge_type)
  File "/app/domain_admin/service/issue_certificate_service.py", line 151, in verify_certificate
    raise AppException("域名验证失败：{}".format(item['domain']))
domain_admin.utils.flask_ext.app_exception.AppException

**Comment by mouday** [comment]
用的是腾讯云吗？

**Comment by SpringAndMay** [comment]
> 用的是腾讯云吗？

不是，是阿里云

**Comment by SpringAndMay** [comment]
使用的镜像来自：https://docker.aityp.com/image/docker.io/mouday/domain-admin:v1.6.37

**Comment by mouday** [comment]
文件下载后，你看下里边的内容，看下是否是对应的值

**Comment by mouday** [comment]
验证文件的内容可能不对

**Comment by SpringAndMay** [comment]
> 验证文件的内容可能不对

重新登陆后台后，重新验证就验证成功了，可能就是部署的文件内容问题
