### ISSUE TITLE
一键部署提示证书获取超时，日志如下，感谢作者

### ISSUE THREAD

**Issue by dislazy** [mouday/domain-admin#120]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/domain_admin/api/issue_certificate_api.py", line 161, in deploy_certificate_file
    issue_certificate_service.renew_certificate(issue_certificate_id)
  File "/app/domain_admin/service/issue_certificate_service.py", line 195, in renew_certificate
    fullchain_pem = acme_v2_api.perform_http01(acme_client, orderr)
  File "/app/domain_admin/utils/acme_util/acme_v2_api.py", line 217, in perform_http01
    raise AppException("证书获取超时")
domain_admin.utils.flask_ext.app_exception.AppException

**Comment by mouday** [comment]
外部网络通畅吗

**Comment by dislazy** [comment]
> 外部网络通畅吗

申请证书的时候很快就申请下来了，这样判断网络是通畅的，我再次试试

**Comment by dislazy** [comment]
刚刚又重新试过了，仍然提示证书下载超时，始终不能一键部署

**Comment by dislazy** [comment]
刚刚又重新试过了，仍然提示证书下载超时，始终不能一键部署

**Comment by mouday** [comment]
点了部署按钮吗？
