### ISSUE TITLE
docker运行后启动报错，提示缺少python的一个什么东西

### ISSUE THREAD

**Issue by mayjack0312** [mouday/domain-admin#24]
安装命令报错
```
docker run \
-v $(pwd)/database:/app/database \
-v $(pwd)/logs:/app/logs \
-p 8000:8000 \
--name domain-admin \
mouday/domain-admin:latest
```

**Comment by mouday** [comment]
可以再描述的详细一点吗？比如操作系统，报错信息

**Comment by HoHoYee** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/domain_admin/main.py", line 12, in <module>
    from domain_admin.router import api_map, permission
  File "/app/domain_admin/router/api_map.py", line 9, in <module>
    from domain_admin.api import system_api
  File "/app/domain_admin/api/system_api.py", line 7, in <module>
    from domain_admin.service import scheduler_service
  File "/app/domain_admin/service/scheduler_service.py", line 7, in <module>
    from pytz_deprecation_shim import PytzUsageWarning
ModuleNotFoundError: No module named 'pytz_deprecation_shim'

**Comment by mouday** [comment]
感谢反馈，版本 v1.2.21 已修复此问题

**Comment by poctopus** [comment]
这个问题在1.4.20上又出现了，可能我很久没更新，刚刚删除了老的镜像，重新拉取镜像后启动，就是这个错误。

**Comment by mouday** [comment]
`pytz_deprecation_shim ` 这个依赖已经移除了，正常不会报这个错了

**Comment by mouday** [comment]
![image](https://github.com/mouday/domain-admin/assets/24365682/417f0e78-f96b-4ce3-ad18-bbb01bc97e9d)

**Comment by jindc123** [comment]
![image](https://github.com/mouday/domain-admin/assets/43500245/8a42b321-7902-4da9-924b-5e911f0816a1)
可以访问到了，但是添加域名时 又有新的报错了
