### ISSUE TITLE
python3.9 login error

### ISSUE THREAD

**Issue by kongtongnali** [mouday/domain-admin#56]
-------------
[2023-08] ERROR in app: Exception on /api/login [POST]
Traceback (most recent call last):
  File "/usr/local/python3.9/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python3.9/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/python3.9/lib/python3.9/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/opt/domain-admin/domain-admin-1.5.15/domain_admin/utils/flask_ext/flask_app.py", line 45, in make_response
    return Response(rv.to_json(), content_type='application/json;charset=utf-8')
  File "/opt/domain-admin/domain-admin-1.5.15/domain_admin/utils/flask_ext/api_result.py", line 31, in to_json
    return json_util.json_encode(self.to_dict())
  File **"/opt/domain-admin/domain-admin-1.5.15/domain_admin/utils/json_util.py"**, line 47, in json_encode
    return json.dumps(data, default=default, **kwargs)
  File "/usr/local/python3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/python3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/python3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected

**Comment by kongtongnali** [comment]
~/domain-admin/domain-admin-1.5.15/domain_admin/utils/flask_ext/api_result.py
# -*- coding: utf-8 -*-
from __future__ import print_function, unicode_literals, absolute_import, division

from domain_admin.utils import json_util


class ApiResult(object):
    """返回统一的数据结构"""

    def __init__(self, data, msg, code):
        self.data = data
        self.msg = msg
        self.code = code

    @classmethod
    def success(cls, data=None, msg='success', code=0):
        return cls(data, msg, code)

    @classmethod
    def error(cls, data=None, msg='error', code=-1):
        return cls(data, msg, code)

    **def to_dict(self):
        return {
            'data': self.data,
            'code': self.code,
            'msg': self.msg
        }

    def to_json(self):
        return json_util.json_encode(self.to_dict())**
